# Generated by Django 2.1.11 on 2021-02-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderMgmtApp', '0002_address_customerx_order_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
