# Generated by Django 3.1.7 on 2024-01-24 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderMgmtApp', '0003_auto_20210222_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CustomerX',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='order',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_Details',
        ),
    ]
