# Generated by Django 5.0.1 on 2024-04-21 04:49

import OrderMgmtApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderMgmtApp', '0004_auto_20240123_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=25, validators=[OrderMgmtApp.validators.validate_firstname]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=25, validators=[OrderMgmtApp.validators.validate_lastname]),
        ),
    ]
