# Generated by Django 5.0.1 on 2024-04-30 05:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderMgmtApp', '0005_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='special_customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_since',
            field=models.DateField(default=datetime.date(2024, 4, 30)),
        ),
        migrations.AddField(
            model_name='customer',
            name='prime_customer',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zipcode', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='OrderMgmtApp.customer')),
            ],
            options={
                'ordering': ['street', 'city', 'state', 'zipcode'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('order_date', models.DateField(default=datetime.date(2024, 4, 30))),
                ('order_total', models.FloatField(default=0)),
                ('payment_type', models.CharField(max_length=1)),
                ('account_number', models.CharField(max_length=20)),
                ('expiration_date', models.DateField(default=2025)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='OrderMgmtApp.customer')),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=25)),
                ('item_quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='OrderMgmtApp.order')),
            ],
            options={
                'ordering': ['item_description'],
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
