# Generated by Django 5.0.1 on 2024-05-04 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderMgmtApp', '0006_alter_customer_options_remove_customer_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_since',
            field=models.DateField(default=datetime.date(2024, 5, 4)),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 5, 4)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2024, 5, 4)),
        ),
    ]
