# Generated by Django 5.0.1 on 2024-05-05 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderMgmtApp', '0008_alter_order_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 5, 4)),
        ),
    ]
